name: C/C++ CI

on:
  push:
    branches: [ quick_add_ci ] # TODO change to master upon finishing testing this config
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: [ubuntu-18.04]
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      fail-fast: false
      matrix:
        compiler: ["/usr/bin/g++"]
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: Install apt Dependencies
      run: sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list' &&
           sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654 &&
           curl -sSL 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC1CF6E31E6BADE8868B172B4F42ED6FBAB17C654' | sudo apt-key add - &&
           sudo apt update && sudo apt -y install build-essential ros-melodic-desktop python-catkin-pkg python-catkin-tools libeigen3-dev git
    - name: Install OpenCV
      run: git clone --branch 3.4 https://github.com/opencv/opencv/ &&
           git clone --branch 3.4 https://github.com/opencv/opencv_contrib/ &&
           mkdir opencv/build/ && cd opencv/build/ && 
           cmake -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules -D BUILD_opencv_java=OFF -D BUILD_opencv_python=OFF .. &&
           make -j2 && sudo make install
    - name: Create Catkin Workspace and compile
      run: export REPO=open_vins_private && cd $GITHUB_WORKSPACE/.. && mkdir src/ &&
           mv $REPO/ src/ && mkdir $REPO/ && mv src/ $REPO/ && cd $REPO/ &&
           source /opt/ros/melodic/setup.bash && catkin build -j2 --no-status # TODO REPO=open_vins
